export default {
  login: "mohammadid52",
  id: 56294878,
  node_id: "MDQ6VXNlcjU2Mjk0ODc4",
  avatar_url: "https://avatars1.githubusercontent.com/u/56294878?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/mohammadid52",
  html_url: "https://github.com/mohammadid52",
  followers_url: "https://api.github.com/users/mohammadid52/followers",
  following_url:
    "https://api.github.com/users/mohammadid52/following{/other_user}",
  gists_url: "https://api.github.com/users/mohammadid52/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/mohammadid52/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/mohammadid52/subscriptions",
  organizations_url: "https://api.github.com/users/mohammadid52/orgs",
  repos_url: "https://api.github.com/users/mohammadid52/repos",
  events_url: "https://api.github.com/users/mohammadid52/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/mohammadid52/received_events",
  type: "User",
  site_admin: false,
  name: "Mohammad Dehgamwala",
  company: null,
  blog: "https://bit.ly/39aW8rd",
  location: "B1-603, Burhani Park, Ahmedabad, Gujarat, India",
  email: null,
  hireable: null,
  bio: "A learning student...",
  twitter_username: "MohammadDehgam6",
  public_repos: 10,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: "2019-10-08T08:01:31Z",
  updated_at: "2020-11-24T08:53:22Z",
};
